version: "3.7"

services:
  grafana:
    build:
      context: .
      args:
        grafana_version: ${GRAFANA_VERSION:-main}
    environment:
      - GF_INSTALL_PLUGINS=grafana-redshift-datasource,grafana-clock-panel
    ports:
      - 3001:3000/tcp
    volumes:
      - ./provisioning:/etc/grafana/provisioning
