name: Latest Grafana API compatibility check
on: [pull_request]

jobs:
  compatibilitycheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
{{#if_eq packageManager "pnpm"}}
      - uses: pnpm/action-setup@v2
{{/if_eq}}
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: '{{ packageManager }}'
      - name: Install dependencies
        run: {{ packageManagerInstallCmd }}
      - name: Build plugin
        run: {{ packageManager }} run build
      - name: Compatibility check
        run: npx @grafana/levitate@latest is-compatible --path src/module.ts --target @grafana/data,@grafana/ui,@grafana/runtime
