version: '3.0'

services:
  grafana:
    container_name: '{{ pluginId }}'
    build:
      context: ./.config
      args:
        grafana_image: ${GRAFANA_IMAGE:-{{~grafanaImage~}} }
        grafana_version: ${GRAFANA_VERSION:-{{~grafanaVersion~}} }
    ports:
      - 3000:3000/tcp
    volumes:
      - ./dist:/var/lib/grafana/plugins/{{ pluginId }}
      - ./provisioning:/etc/grafana/provisioning
