version: '3.0'

services:
  grafana:
    container_name: '{{ normalize_id pluginName orgName pluginType }}'
    build:
      context: ./.config
      args:
        grafana_version: ${GRAFANA_VERSION:-{{~grafanaVersion~}} }
    ports:
      - 3000:3000/tcp
    volumes:
      - ./dist:/var/lib/grafana/plugins/{{ normalize_id pluginName orgName pluginType }}
      - ./provisioning:/etc/grafana/provisioning
