{{!-- /* 🚨 The `${{ }}` Github workflow expressions need to be escaped so they are not being interpreted by Handlebars. (this comment is going to be removed after scaffolding) 🚨 */ --}}
name: CI

on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
{{#if_eq packageManagerName "pnpm"}}
      # pnpm action uses the packageManager field in package.json to
      # understand which version to install.
      - uses: pnpm/action-setup@v2
{{/if_eq}}
      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: '{{ packageManagerName }}'

      - name: Install dependencies
        run: {{ packageManagerInstallCmd }}

      - name: Check types
        run: {{ packageManagerName }} run typecheck
      - name: Lint
        run: {{ packageManagerName }} run lint
      - name: Unit tests
        run: {{ packageManagerName }} run test:ci
      - name: Build frontend
        run: {{ packageManagerName }} run build

      - name: Start grafana docker
        run: docker-compose up -d

      - name: Run e2e tests
        run: {{ packageManagerName }} run e2e

      - name: Stop grafana docker
        run: docker-compose down

      - name: Check for backend
        id: check-for-backend
        run: |
          if [ -f "Magefile.go" ]
          then
            echo "has-backend=true" >> $GITHUB_OUTPUT
          fi

      - name: Setup Go environment
        if: steps.check-for-backend.outputs.has-backend == 'true'
        uses: actions/setup-go@v3
        with:
          go-version: '1.19'

      - name: Test backend
        if: steps.check-for-backend.outputs.has-backend == 'true'
        uses: magefile/mage-action@v2
        with:
          version: latest
          args: coverage

      - name: Build backend
        if: steps.check-for-backend.outputs.has-backend == 'true'
        uses: magefile/mage-action@v2
        with:
          version: latest
          args: buildAll
