name: Deploy to Developer Portal Bucket

on:
  push:
    branches:
      - main
      - feat/deploy-to-dev-portal
    paths:
      - '.github/workflows/deploy-to-developer-portal.yml'
      - 'docusaurus/**'

jobs:
  deploy:
    name: Deploy docs to Developer Portal Bucket
    runs-on: ubuntu-latest
    steps:
      - name: Generate token
        id: generate_token
        uses: tibdex/github-app-token@b62528385c34dbc9f38e5f4225ac829252d1ea92
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_PEM }}

      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          registry-url: 'https://registry.npmjs.org'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci
      
      - name: Build documentation website
        run: npm run docs:build
        
      - id: 'auth'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
      - name: Deploy to Developer Portal Bucket
        uses: google-github-actions/upload-cloud-storage@v1
        with:
          path: './docusaurus/website/build/*'
          destination: 'grafana_developer_portal/plugin-tools'
