name: Create-plugin NPM bump version

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Semver type of new version (major / minor / patch)'
        required: true
        type: choice
        options:
          - patch
          - minor
          - major

jobs:
  create-plugin-bump-version:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_BOT_ACCESS_TOKEN }}

      - name: Setup environment
        uses: actions/setup-node@v3.1.1
        with:
          node-version: '16'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --immutable

      - name: Check types
        run: yarn typecheck
        working-directory: './packages/create-plugin'

      - name: Lint
        run: yarn lint
        working-directory: './packages/create-plugin'

      - name: Build
        run: yarn build
        working-directory: './packages/create-plugin'

      - name: Unit tests
        run: yarn test
        working-directory: './packages/create-plugin'

      - name: Setup Git
        run: |
          git config user.name 'grafanabot'
          git config user.email 'bot@grafana.com'
      
      - name: bump create-plugin version
        run: yarn version --${{ github.event.inputs.version }}
        working-directory: './packages/create-plugin'
      
      - name: Push latest version
        run: git push origin main --follow-tags
