name: E2E tests - Playwright
on:
  pull_request:
    paths:
      - 'packages/plugin-e2e/**'
      - '.github/workflows/playwright.yml'

jobs:
  setup-matrix:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    outputs:
      matrix: ${{ steps.resolve-versions.outputs.matrix }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Resolve Grafana E2E versions
        id: resolve-versions
        uses: grafana/plugin-actions/e2e-version@main
        with:
          version-resolver-type: version-support-policy

  playwright-tests:
    needs: setup-matrix
    timeout-minutes: 60
    strategy:
      matrix:
        GRAFANA_VERSION: ${{fromJson(needs.setup-matrix.outputs.matrix)}}
    name: E2E Tests - Grafana@${{ matrix.GRAFANA_VERSION }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - id: get-secrets
        uses: grafana/shared-workflows/actions/get-vault-secrets@main
        with:
          repo_secrets: |
            GCP_GRAFANA_UPLOAD_ARTIFACTS_KEY=infra/data/ci/grafana/releng/artifacts-uploader-service-account:GCP_GRAFANA_UPLOAD_ARTIFACTS_KEY
      - name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ env.GCP_GRAFANA_UPLOAD_ARTIFACTS_KEY }}'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'

      - name: Copy auth file
        run: mkdir -p packages/plugin-e2e/playwright/.auth/ && cp .github/user.json packages/plugin-e2e/playwright/.auth/user.json

      - name: Setup Node.js environment
        uses: actions/setup-node@v4

      - name: Install dependencies
        run: npm ci

      - name: Build frontend
        run: npm run build --w @grafana/plugin-e2e

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps chromium

      - name: Start Grafana
        run: docker run --rm -d -p 3000:3000 --name=grafana --volume ./packages/plugin-e2e/provisioning:/etc/grafana/provisioning --env AWS_SECRET_ACCESS_KEY=${{secrets.AWS_SECRET_ACCESS_KEY}} --env AWS_ACCESS_KEY_ID=${{secrets.AWS_ACCESS_KEY_ID}} --env GOOGLE_JWT_FILE=${{secrets.GOOGLE_JWT_FILE}} --env "GF_INSTALL_PLUGINS=grafana-googlesheets-datasource 1.2.4,grafana-redshift-datasource 1.13.0,grafana-clock-panel 2.1.3" grafana/grafana:${{ matrix.GRAFANA_VERSION }}; sleep 30

      - name: Run Playwright tests
        run: npm run playwright:test --w @grafana/plugin-e2e
        env:
          GOOGLE_JWT_FILE: ${{ secrets.GOOGLE_JWT_FILE }}

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report-Grafana-v${{ matrix.GRAFANA_VERSION }}-${{github.run_id}}
          path: packages/plugin-e2e/playwright-report/
          retention-days: 30

      - name: Publish report to Cloud Storage
        run: |
          echo "Publish release to Google Cloud Storage:"
          gsutil cp -r packages/plugin-e2e/playwright-report/. gs://releng-pipeline-artifacts-dev/plugin-name/${{ github.event.number }}/Grafana${{ matrix.GRAFANA_VERSION }}
