name: Test docs build

on:
  pull_request:
    branches:
      - main
    paths:
      - '.github/workflows/deploy.yml'
      - '.github/workflows/test-build.yml'
      - 'docusaurus/**'

jobs:
  deploy:
    name: Build docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          registry-url: 'https://registry.npmjs.org'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci
      - name: Build documentation website (GH Pages)
        run: npm run docs:build
      - name: Clear documentation build
        run: npm run docs:clear
      - name: Make docs the homepage of this subsite (Dev Portal)
        run: |
          rm -f ./docusaurus/website/src/pages/index.tsx
          sed -i 's/title: Get started/title: Get started\nslug:\ \//g' ./docusaurus/docs/get-started/get-started.mdx
          grep -rl "](/docs/" docusaurus/docs | xargs sed -i 's/](\/docs\//](\//g'
      - name: Build documentation website (Dev Portal)
        run: npm run docs:build -- --config docusaurus.config.devportal.js
