name: test-and-publish
on: push

jobs:
  test:
    runs-on: ubuntu-latest
    name: Run unit tests
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
      - name: Install dependencies
        run: yarn
      - name: Check types
        run: yarn typecheck
      - name: Lint
        run: yarn lint
      - name: Unit tests
        run: yarn jest
  version_check:
    name: Check version to publish
    runs-on: ubuntu-latest
    needs: test
    # if: github.ref == 'refs/heads/main'
    outputs:
      changed_version: ${{ steps.version_check.outputs.changed }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
      # limit releases to version changes - https://github.com/EndBug/version-check
      - name: Check version changes
        uses: EndBug/version-check@v1
        id: version_check
        with:
          # diff the commits rather than commit message for version changes
          diff-search: true

      - name: Version update detected
        if: steps.version_check.outputs.changed == 'true'
        run: 'echo "Version change found! New version: ${{ steps.version_check.outputs.version }} (${{ steps.version_check.outputs.type }})"'
  publish:
    name: Publish to NPM Package Registry
    runs-on: ubuntu-latest
    needs: version_check
    if: github.jobs.checkversion.outputs.changed_version
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
      - name: Setup .npmrc file for NPM registry
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          registry-url: 'https://registry.npmjs.org'
      - name: Install dependencies
        run: yarn
      - name: Build library
        run: yarn build
      - name: Publish package to NPM
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
