name: Test docs build

on:
  pull_request:
    branches:
      - main
    paths:
      - '.github/workflows/deploy-to-developer-portal-dev.yml'
      - '.github/workflows/deploy-to-developer-portal-prod.yml'
      - '.github/workflows/test-build.yml'
      - 'docusaurus/**'

jobs:
  deploy:
    name: Build docs
    runs-on: ubuntu-latest
    env:
      NX_SKIP_NX_CACHE: 'true'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          registry-url: 'https://registry.npmjs.org'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci      
      - name: Build documentation website (Dev Portal)
        run: npm run docs:build
