name: test-and-publish
on: push

jobs:
  test:
    runs-on: ubuntu-latest
    name: Run unit tests
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
      - name: Setup .npmrc file for NPM registry
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          registry-url: 'https://registry.npmjs.org'
      - name: Install dependencies
        run: yarn
      - name: Check types
        run: yarn typecheck
      - name: Lint
        run: yarn lint
      - name: Unit tests
        run: yarn jest
      - name: test an app plugin generation
        run: yarn generate-app && (cd generated && yarn && yarn build && yarn lint)
      - name: test panel plugin generation
        run: yarn generate-panel && (cd generated && yarn && yarn build && yarn lint)
      - name: test datasource plugin generation
        run: yarn generate-datasource && (cd generated && yarn && yarn build && yarn lint)
  publish:
    name: Publish to NPM Package Registry
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: main
      # limit releases to version changes - https://github.com/EndBug/version-check
      - name: Check version changes
        uses: EndBug/version-check@v1
        id: version_check
        with:
          # diff the commits rather than commit message for version changes
          diff-search: true

      - name: Version update detected
        if: steps.version_check.outputs.changed == 'true'
        run: 'echo "Version change found! New version: ${{ steps.version_check.outputs.version }} (${{ steps.version_check.outputs.type }})"'

      - name: Setup .npmrc file for NPM registry
        if: steps.version_check.outputs.changed == 'true'
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        if: steps.version_check.outputs.changed == 'true'
        run: yarn

      - name: Build library
        if: steps.version_check.outputs.changed == 'true'
        run: yarn build

      - name: Publish package to NPM
        if: steps.version_check.outputs.changed == 'true'
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
