name: Test docs build

on:
  pull_request:
    branches:
      - main

jobs:
  deploy:
    name: Build docs
    runs-on: ubuntu-latest
    env:
      NX_CLOUD_ACCESS_TOKEN: ${{ secrets.NX_CLOUD_ACCESS_TOKEN }}
      NX_BRANCH: ${{ github.event.number || github.ref_name }}
    steps:
      - name: Check for docs file changes
        uses: dorny/paths-filter@v2.11.1
        id: filter
        with:
          filters: |
            docs:
              - '.github/workflows/deploy-to-developer-portal-dev.yml'
              - '.github/workflows/deploy-to-developer-portal-prod.yml'
              - '.github/workflows/test-build.yml'
              - 'docusaurus/**'
              - 'package-lock.json'
      - name: Checkout repository
        if: ${{ steps.filter.outputs.docs == 'true' }}
        uses: actions/checkout@v4
      - name: Setup node
        if: ${{ steps.filter.outputs.docs == 'true' }}
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'
          cache: 'npm'
      - name: Install dependencies
        if: ${{ steps.filter.outputs.docs == 'true' }}
        run: npm ci
      - name: Build documentation website (Dev Portal)
        if: ${{ steps.filter.outputs.docs == 'true' }}
        run: npm run docs:build
